# Docker Compose for ConvNeXt Pipeline
version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convnext-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./data:/app/data:ro
    environment:
      - MODEL_PATH=/app/models/best_model.pth
      - THEME=classification
      - LOG_LEVEL=INFO
      - MAX_WORKERS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Monitoring (Prometheus - optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: convnext-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./production/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
  
  # Grafana Dashboard (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: convnext-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
